name: Consume RAM Test

on: [push]

jobs:
  consume_ram_job:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
        
    - name: Run script to consume RAM
      run: python consume_memory.py
